export const CATEGORIE_GET_API = "CATEGORIE_GET_API";
export const CATEGORIE_POST_API = "CATEGORIE_POST_API";
// export const CATEGORIE_GET_SINGLE_API = "CATEGORIE_GET_API";
// export const CATEGORIE_PUT_API = "CATEGORIE_GET_API";
// export const CATEGORIE_DELETE_API = "CATEGORIE_GET_API";
